# Generated by Django 5.2 on 2025-04-17 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('encrypted_data', models.BinaryField()),
                ('encrypted_key', models.BinaryField()),
                ('iv', models.BinaryField()),
                ('c1', models.TextField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'EncryptedImageModel',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('otp', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'UserModel',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='static/assets/UserProfiles')),
                ('bio', models.TextField()),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
        migrations.CreateModel(
            name='RequestFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.EmailField(max_length=254)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('otp', models.IntegerField(null=True)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.encryptedimage')),
            ],
            options={
                'db_table': 'RequestFileModel',
            },
        ),
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/assetsFiles')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=100)),
                ('datahash', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermodel')),
            ],
            options={
                'db_table': 'UploadFileModel',
            },
        ),
        migrations.AddField(
            model_name='encryptedimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermodel'),
        ),
    ]
